name: Build Quest Mod

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: QPM Action
      uses: Fernthedev/qpm-action@v1
      with:
        workflow_token: ${{ secrets.GITHUB_TOKEN }}
        restore: true
        cache: true
        resolve_ndk: true

    - name: Build
      run: |
        qpm s build

    - name: Create QMOD
      run: |
        qpm s qmod

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: vivify-qmod
        path: ./*.qmod

    - name: Publish Release
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v2
      with:
        name: Vivify 0.4
        body: vivify yayy
        files: ./*.qmod
